#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in5,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in6,    leftTracker,    sensorLineFollower)
#pragma config(Sensor, in7,    centerTracker,  sensorLineFollower)
#pragma config(Sensor, in8,    rightTracker,   sensorLineFollower)
#pragma config(Sensor, dgtl6,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl7,  button,         sensorTouch)
#pragma config(Sensor, dgtl10, sonarSensor,    sensorSONAR_inch)
#pragma config(Sensor, I2C_1,  rightIEM,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftIEM,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftMotor,     tmotorVex269_HBridge, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex269_HBridge, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void stop(){
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	stopAllMotors();

}
void forward(){
	motor[leftMotor] = 60;
	motor[rightMotor] = 60;
}
void closeClaw(){
	motor[clawMotor] = 40;
	wait1Msec(1000);
	motor[clawMotor] = 0;

}
void waitForInput(){
	displayNextLCDString("-->Push Button or Switch to continue<--");
	while(SensorValue(button) == 0 && SensorValue(limitSwitch) == 0 ){

	}
}
void openClaw(){
	motor[clawMotor] = -40;
	wait1Msec(1000);
	motor[clawMotor] = 0;
}

void slowForward(){
	motor[leftMotor] = 30;
	motor[rightMotor] = 30;
}


void left(){
	stop();
	motor[rightMotor] = 63;
	wait1Msec(1000);
	stop();
}

void right(){
	stop();
	motor[leftMotor]  = 63;
	wait1Msec(1000);
	stop();
}
void clearEncoders(){
	//Clear the encoders associated with the left and right motors
	nMotorEncoder[rightMotor] = 0;
	nMotorEncoder[leftMotor] = 0;

}

void reverse(){
	motor[leftMotor] = -60;
	motor[rightMotor] = -60;
}


void slowReverse(){
	motor[leftMotor] = -30;
	motor[rightMotor] = -30;
}

task main()
{

	clearLCDLine(1);
	displayLCDPos(1,0);                                   // Set the cursor to bottom line, first position
	//displayNextLCDString("Potentio: ");                   // Print "Potentio: " starting at the cursor position
	//displayNextLCDNumber(SensorValue(armPot));    // Display the reading of the Potentiometer to current cursor position

	while(SensorValue(button) == 0 && SensorValue(limitSwitch) == 0 ){
		displayNextLCDString("-->Push Button or Switch to Start <--");
	}
	displayNextLCDString("-->Ready to Demo Potentiometer<--");
	wait1Msec(3000);
	displayNextLCDString("-->Demoing Potentiometer...<--");
	while(SensorValue(button) == 0 && SensorValue(limitSwitch) == 0){
		while(SensorValue(armMotor) < 500){
			motor[armMotor] = 40;
		}
		motor[armMotor] = 0;
		wait1Msec(2000);
		while(SensorValue(armMotor) > 500){
			motor[armMotor] = -40;
		}
		motor[armMotor] = 0;
		wait1Msec(2000);
	}
	motor[armMotor] = 0;
	waitForInput();

	//38cm to inches = 14.9inches
	//ticks goal =  (29 * 149) / 10 = 432 ticks
	int tickGoal = 432;
	while(nMotorEncoder[rightMotor] < tickGoal){
		displayNextLCDString("Searching For Item...");
		slowForward();
	}
	stop();
	clearEncoders();
	//Find the item
	if(SensorValue(sonarSensor) == -1){
		displayNextLCDString("Cannot Locate Item!");
		stop();
		}else{
		//Item found, continue with challenge
		displayNextLCDString("Waiting...");
		wait1Msec(2000);
		openClaw();
		wait1Msec(1000);
		displayNextLCDString("Picking Up Item...");
		closeClaw();
		wait1Msec(2000);
		displayNextLCDString("Turning Left...");
		left();
		wait1Msec(2000);
		displayNextLCDString("Forward...");
		forward();
		wait(2000);
		stop();
		displayNextLCDString("Dropping Item...");
		openClaw();
		wait1Msec(3000);
		displayNextLCDString("Reversing...");
		reverse();
		wait1Msec(2000);
		stop();

	}
	displayNextLCDString("Done!");
}
