#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in5,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in6,    leftTracker,    sensorLineFollower)
#pragma config(Sensor, in7,    centerTracker,  sensorLineFollower)
#pragma config(Sensor, in8,    rightTracker,   sensorLineFollower)
#pragma config(Sensor, I2C_1,  rightIEM,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftIEM,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftMotor,     tmotorVex269_HBridge, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex269_HBridge, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(true)
  {
    clearLCDLine(1);                                      // Clear LCD Bottom Line

    displayLCDPos(1,0);                                   // Set the cursor to bottom line, first position
    displayNextLCDString("Potentio: ");                   // Print "Potentio: " starting at the cursor position

    displayNextLCDNumber(SensorValue(armPot));    // Display the reading of the Potentiometer to current cursor position

    while(SensorValue(centerTracker) > 1000|| SensorValue(leftTracker) > 1000 || SensorValue(rightTracker) > 1000)
    {
    	forward();


    }



    while(SensorValue(armPot) < 2000){
    	motor[armMotor] = 40;
    	motor[clawMotor] = 50;
    	//motor[leftMotor] = 60;
    	//motor[rightMotor] = 0;
  	}
  	while(SensorValue(armPot) > 1550){
    	motor[armMotor] = -25;
    	//motor[leftMotor] = 0;
    	motor[clawMotor] = -50;
    	//motor[rightMotor] = 40;
  	}

    wait1Msec(150);                                       // Wait 150 milliseconds to help the LCD refresh nicely
  }

}

void stop(){
	motor[leftMotor] = 0;
  motor[rightMotor] = 0;
}


void forward(){
	motor[leftMotor] = 60;
  motor[rightMotor] = 60;
}


void slowForward(){
	motor[leftMotor] = 30;
  motor[rightMotor] = 30;
}


void left(){
	stop();
  while( nMotorEncoder[leftMotor] < 1000)
	{
		motor[rightMotor]  = 63;
		}
		stop();
}

void right(){
	stop();
  while( nMotorEncoder[rightMotor] < 1000)
	{
		motor[leftMotor]  = 63;
	}
	stop();
}

void reverse(){
	motor[leftMotor] = -60;
  motor[rightMotor] = -60;
}


void slowReverse(){
	motor[leftMotor] = -30;
  motor[rightMotor] = -30;
}
