#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in5,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in6,    leftTracker,    sensorLineFollower)
#pragma config(Sensor, in7,    centerTracker,  sensorLineFollower)
#pragma config(Sensor, in8,    rightTracker,   sensorLineFollower)
#pragma config(Sensor, dgtl6,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl3,  button,         sensorTouch)
#pragma config(Sensor, dgtl10, sonarSensor,    sensorSONAR_inch)
#pragma config(Sensor, I2C_1,  rightIEM,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftIEM,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftMotor,     tmotorVex269_HBridge, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex269_HBridge, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void stop_(){

	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	stopAllMotors();

}
void forward(){
	motor[leftMotor] = 60;
	motor[rightMotor] = 60;
}
void closeClaw(){
	motor[clawMotor] = 30;
	wait1Msec(1000);
	motor[clawMotor] = 0;

}
void waitForInput(){
	displayNextLCDString("-->Push Button or Switch to continue<--");
	while(SensorValue(button) == 0 && SensorValue(limitSwitch) == 0 ){

	}
}
bool isHoldingItem(){
return (sensorValue(limitSwitch) == 1);
}
void openClaw(){
	motor[clawMotor] = -30;
	wait1Msec(1500);
	motor[clawMotor] = 0;
}

void slowForward(){
	motor[leftMotor] = 34;
	motor[rightMotor] = 34;
}


void left(){
	stop_();
	motor[rightMotor] = 63;
	motor[leftMotor] = -40;
	wait1Msec(1450);
	stop_();
}

void right(){
	stop_();
	motor[leftMotor]  = 63;
	wait1Msec(2500);
	stop_();
}
void clearEncoders(){
	//Clear the encoders associated with the left and right motors
	nMotorEncoder[rightMotor] = 0;
	nMotorEncoder[leftMotor] = 0;

}

void reverse(){
	motor[leftMotor] = -60;
	motor[rightMotor] = -60;
}


void slowReverse(){
	motor[leftMotor] = -30;
	motor[rightMotor] = -30;
}

task main()
{

	clearLCDLine(1);
	displayLCDPos(1,0);                                   // Set the cursor to bottom line, first position
	//displayNextLCDString("Potentio: ");                   // Print "Potentio: " starting at the cursor position
	//displayNextLCDNumber(SensorValue(armPot));    // Display the reading of the Potentiometer to current cursor position



//Setup the VEX LCD for displaying encoder values
clearLCDLine(0);
clearLCDLine(1);
displayLCDString(0, 0, "R: ");
displayLCDString(1, 0, "L: ");

//Clear the encoders associated with the left and right motors
nMotorEncoder[rightMotor] = 0;
nMotorEncoder[leftMotor] = 0;

	while(SensorValue(button) == 0 && SensorValue(limitSwitch) == 0 ){
		displayNextLCDString("-->Push Button or Switch to Start <--");
	}

	//38cm to inches = 14.9inches
	//ticks goal =  (29 * 149) / 10 = 432 ticks
	int tickGoal = 432;
	displayNextLCDString("Searching For Item...");
	while(nMotorEncoder[rightMotor] < tickGoal){
		slowForward();
	}
	openClaw();
	clearEncoders();
	wait1Msec(1000);
	clearLCDLine(0);
clearLCDLine(1);
displayLCDString(0, 0, "R: ");
displayLCDString(1, 0, "L: ");
	//Find the item
	if(SensorValue(sonarSensor) == -1 || SensorValue(sonarSensor) > 20){
		displayNextLCDString("Cannot Locate Item!");
		stop_();
	}else{
		//Item found, continue with challenge
		stop_();
		displayNextLCDString("Waiting...");
		waitForInput();
		openClaw();
		wait1Msec(2000);
		clearLCDLine(1);
		displayNextLCDString("Picking Up Item...");
		closeClaw();
		wait1Msec(2000);
		clearLCDLine(0);
clearLCDLine(1);
	if(isHoldingItem()){
		displayNextLCDString("Turning Left...");
		clearLCDLine(0);
		clearLCDLine(1);
		left();
	}else{
		stop_();
	}
		wait1Msec(2000);
		displayNextLCDString("Forward...");
		clearLCDLine(0);
clearLCDLine(1);
displayLCDString(0, 0, "R: ");
displayLCDString(1, 0, "L: ");
if(isHoldingItem()){
		forward();
		wait1Msec(2000);
		stop_();
		wait1Msec(1000);
		displayNextLCDString("Dropping Item...");
		clearLCDLine(0);
clearLCDLine(1);
displayLCDString(0, 0, "R: ");
displayLCDString(1, 0, "L: ");
		openClaw();
}else{
	stop_();
	displayNextLCDString("is item gone?...");
}
		wait1Msec(3000);
		clearLCDLine(1);
		clearLCDLine(0);
		displayNextLCDString("Reversing...");
		clearLCDLine(0);
clearLCDLine(1);
displayLCDString(0, 0, "R: ");
displayLCDString(1, 0, "L: ");
		reverse();
		wait1Msec(2000);
		stop_();

	}
clearLCDLine(0);
clearLCDLine(1);
displayLCDString(0, 0, "R: ");
displayLCDString(1, 0, "L: ");
	displayNextLCDString("Done!");
}
